# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
image:
  registry: ghcr.io
  repsitory: serhii-cherkez
  tag: v1.0.8.8-015fdc2
  os: linux
  arch: amd64
service:
  port: 8080
secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN
