# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: ghcr.io
  repsitory: serhii-cherkez
  tag: 1.0.7.8
  os: linux
  arch: amd64

service:
  port: 8080

secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN