name: kbot-CICD

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
        with:
          fetch_dept: 0

      - name: Run test
        run: make test

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Build and Push
        env:
          APP: kbot
          REGISTRY: ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}
        run: make image push