name: kbot-CICD

on: 
  push:
    branches:
    - development

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
        with:
          fetch_dept: 0

      - name: Run test
        run: make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        env:
          APP: kbot
          REPOSITORY: ghcr.io
          NAMESPACE: serhii-cherkez
          VERSION: $(shell git describe --tags --abbrev=0)-$(shell git rev-parse --short HEAD)
          TARGETOS: linux
          TARGETARCH: amd64
        run: make image push