name: SOPS-KMS-FLUX

on: 
  push:
    branches:
    - main

jobs:
  cloudrun:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/721962795719/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: github-actions-service-account@prometheus-devops-course.iam.gserviceaccount.com

      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: kbot-gke-cluster
          location: us-central1-c

      - id: get-pods
        run: kubectl get pods